//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurseEntities : DbContext
    {
        private static CurseEntities context;
        public static CurseEntities GetContext()
        {
            if (context == null)
                context = new CurseEntities();
            return context;

        }
        public static Staff CurrentStaff;
        public static Staff currentStaff
        {
            get
            {
                if (CurrentStaff == null)
                    CurrentStaff = new Staff();
                return CurrentStaff;
            }
            set
            {
                CurrentStaff = value;
            }
        }
        
        public CurseEntities()
            : base("name=CurseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Klients> Klients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
    }
}
